stages:
  - build
  - test
  - package
  - deploy

image: maven:latest

cache:
  paths:
    - service1/maven.repository/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=maven.repository"

build-app:
  stage: build
  script:
    - mvn package -DskipTests -B
  artifacts:
    paths:
      - target
    expire_in: 1 week

test-app:
  stage: test
  script:
    - mvn test -B
  dependencies:
    - build-app
